"""All wording in one place, per language.

To change how anything reads in Telegram, edit this file only.
Technical terms (OI, Funding, RVOL, SL, TP, MA, %B) stay in English on
purpose: that is how they read on the exchange and the chart.
"""
from __future__ import annotations

TERMS: dict[str, dict] = {
    "ar": {
        # headline: what to do, before any detail
        "action": {
            "LONG": "🟢 LONG",
            "SHORT": "🔴 SHORT",
            "NO_LONG": "⛔ ممنوع LONG",
            "NO_SHORT": "⛔ ممنوع SHORT",
            "WATCH_long": "👀 مراقبة LONG",
            "WATCH_short": "👀 مراقبة SHORT",
        },
        "bounce": "ارتداد",
        # signal type: why
        "type": {
            "EARLY_BREAKOUT": "🚀 اختراق مبكر",
            "CONTINUATION": "📈 استمرار ترند",
            "SQUEEZE_RISK": "⚠️ خطر Squeeze",
            "SHORT_SQUEEZE": "💥 Short squeeze",
            "NEW_SHORTS": "🔻 شورتات جديدة",
            "LONG_LIQUIDATION": "🩸 تصفية لونجات",
            "LATE_PUMP": "🛑 بامب متأخر",
            "VOLUME_SPIKE": "🔊 فوليوم غير طبيعي",
            "EARLY_15M": "⚡ إنذار مبكر 15m",
        },
        "trend": {"up": "صاعد", "down": "هابط", "flat": "عرضي", "unknown": "غير واضح"},
        "score": "التقييم",
        "confirmed": "✅ مؤكدة على المنصتين: {exs}",
        "single": "📍 المنصة: {exs} بس",
        "candle": "🕐 الشمعة: {window} بتوقيت القاهرة",
        # plan block
        "plan_h": "📌 <b>الخطة</b>",
        # each line starts with an Arabic word so Telegram lays it out right-to-left
        "plan_lines": {
            "entry": "الدخول: {entry}",
            "sl": "🛑 وقف الخسارة (SL): {sl} ({sl_pct})",
            "tp1": "🎯 الهدف الأول (TP1): {tp1} ({tp1_pct}){proj}",
            "tp2": "🎯 الهدف التاني (TP2): {tp2} ({tp2_pct}){proj}",
            "size": "💵 الحجم: {qty} {coin} (~{notional}) لمخاطرة {risk}",
        },
        "projected": " محسوب",
        "read_h": "📊 <b>القراءة</b>",
        "read_lines": [
            "• الفوليوم: {rvol} من متوسط 20 ساعة",
            "• حركة السعر: {chg} في الساعة",
            "• الـ OI: {oi} في الساعة",
            "• الـ Funding: {funding}",
            "• نسبة الشراء (Taker buy): {taker}",
            "• فريم 4h: {ma} · %B {pctb}",
            "• البعد عن قاع 7 أيام: {from_low}",
        ],
        "ma_above": "فوق MA5/10/20",
        "ma_below": "تحت MA5/10/20",
        "ma_mixed": "فوق MA{list}",
        "ma_none": "تحت المتوسطات",
        # levels block (for warnings/watch, where there is no plan)
        "lv_h": "🧱 <b>المستويات</b>",
        "res": "المقاومة",
        "sup": "الدعم",
        "none_near": "مفيش قريب",
        "notes_h": "📝 <b>ملاحظات</b>",
        "notes": {
            "counter_trend": "⚠️ <b>عكس الترند:</b> ترند الـ 4h {arg}، اعتبرها صفقة تصحيح",
            "projected_long": "مفيش مقاومة فوق السعر، فالـ TP محسوب على 1.5R و 3R",
            "projected_short": "مفيش دعم تحت السعر، فالـ TP محسوب على 1.5R و 3R",
            "wide_sl": "الـ SL واسع ({arg}%)، والحجم اتقلل على قده",
            "oi_na": "مفيش داتا OI للعملة دي",
            "late": "السعر طار خلاص: متطاردش اللونج",
            "short_squeeze": "الصعود جاي من قفل شورتات مش فلوس جديدة، والحركة غالبًا قصيرة",
            "squeeze_risk": "الـ Funding سالب والـ OI طالع: الشورتات متزاحمة",
            "funding_neg": "الـ Funding سالب: الشورتات متزاحمة، متدخلش شورت",
            "liq_flush": "نزول بسبب تصفية لونجات، والارتداد عكس الحركة: التزم بالـ SL",
            "no_oi_confirm": "مفيش فلوس جديدة داخلة (الـ OI مطلعش)، استنى تأكيد",
        },
        # other messages
        "early_body": "الفوليوم: {rvol} من المتوسط\nحركة السعر: {chg} في 15 دقيقة\nالسعر: {price}\nاستنى قفل شمعة الساعة للتأكيد",
        "started": "🟢 <b>الـ Volume Scanner اشتغل</b>\nالمنصات: {exs}\nحفظ الحالة: {state}",
        "state_memory": "ذاكرة مؤقتة (بتتمسح مع الـ restart)",
        "state_redis": "Redis",
        "hb_h": "💓 <b>الـ Scanner شغال</b>",
        "hb_row": "{ex}: {eligible} من {contracts} عقد · {spikes} spikes",
        "hb_took": "مدة آخر scan: {took}",
        "err_h": "🔴 <b>مشكلة في الـ Scanner</b>",
        "sum_h": "📊 <b>الملخص اليومي</b>",
        "sum_none": "مفيش إشارات في آخر 24 ساعة.",
        "sum_count": "عدد الإشارات (24 ساعة): {n}",
        "sum_best": "🏆 أحسن 3:",
        "sum_worst": "📉 أسوأ 3:",
        "sum_win": "✅ نسبة النجاح (آخر 7 أيام):",
    },
    "en": {
        "action": {
            "LONG": "🟢 LONG",
            "SHORT": "🔴 SHORT",
            "NO_LONG": "⛔ NO LONG",
            "NO_SHORT": "⛔ NO SHORT",
            "WATCH_long": "👀 WATCH LONG",
            "WATCH_short": "👀 WATCH SHORT",
        },
        "bounce": "bounce",
        "type": {
            "EARLY_BREAKOUT": "🚀 Early breakout",
            "CONTINUATION": "📈 Continuation",
            "SQUEEZE_RISK": "⚠️ Squeeze risk",
            "SHORT_SQUEEZE": "💥 Short squeeze",
            "NEW_SHORTS": "🔻 New shorts",
            "LONG_LIQUIDATION": "🩸 Long liquidation",
            "LATE_PUMP": "🛑 Late pump",
            "VOLUME_SPIKE": "🔊 Volume spike",
            "EARLY_15M": "⚡ Early warning 15m",
        },
        "trend": {"up": "up", "down": "down", "flat": "flat", "unknown": "unclear"},
        "score": "Score",
        "confirmed": "✅ Confirmed on {exs}",
        "single": "📍 {exs} only",
        "candle": "🕐 Candle {window} (Cairo)",
        "plan_h": "📌 <b>Plan</b>",
        "plan_lines": {
            "entry": "Entry: {entry}",
            "sl": "🛑 Stop (SL): {sl} ({sl_pct})",
            "tp1": "🎯 Target 1 (TP1): {tp1} ({tp1_pct}){proj}",
            "tp2": "🎯 Target 2 (TP2): {tp2} ({tp2_pct}){proj}",
            "size": "💵 Size: {qty} {coin} (~{notional}) for {risk} risk",
        },
        "projected": " projected",
        "read_h": "📊 <b>Reading</b>",
        "read_lines": [
            "• Volume: {rvol} vs 20h average",
            "• Price move: {chg} in 1h",
            "• OI: {oi} in 1h",
            "• Funding: {funding}",
            "• Taker buy: {taker}",
            "• 4h: {ma} · %B {pctb}",
            "• From 7d low: {from_low}",
        ],
        "ma_above": "above MA5/10/20",
        "ma_below": "below MA5/10/20",
        "ma_mixed": "above MA{list}",
        "ma_none": "below the MAs",
        "lv_h": "🧱 <b>Levels</b>",
        "res": "Resistance",
        "sup": "Support",
        "none_near": "none nearby",
        "notes_h": "📝 <b>Notes</b>",
        "notes": {
            "counter_trend": "⚠️ <b>Counter-trend:</b> 4h trend is {arg}, treat as a pullback trade",
            "projected_long": "No resistance above price: TP projected at 1.5R / 3R",
            "projected_short": "No support below price: TP projected at 1.5R / 3R",
            "wide_sl": "SL is wide ({arg}%), size reduced accordingly",
            "oi_na": "OI data unavailable",
            "late": "Move already extended: do not chase the long",
            "short_squeeze": "Rise driven by shorts closing, not new money: likely short-lived",
            "squeeze_risk": "Funding negative + OI rising: shorts crowded",
            "funding_neg": "Funding negative: shorts crowded, do not short",
            "liq_flush": "Drop driven by long liquidations; bounce is counter-move, respect the SL",
            "no_oi_confirm": "No new money (OI not rising): wait for confirmation",
        },
        "early_body": "Volume {rvol} vs average · move {chg} · price {price}\nWatch the 1h close for confirmation",
        "started": "🟢 <b>Volume Scanner started</b>\nExchanges: {exs}\nState: {state}",
        "state_memory": "memory (cleared on restart)",
        "state_redis": "Redis",
        "hb_h": "💓 <b>Heartbeat</b>",
        "hb_row": "{ex}: {eligible}/{contracts} scanned · {spikes} spikes",
        "hb_took": "Last scan: {took}",
        "err_h": "🔴 <b>Scanner error</b>",
        "sum_h": "📊 <b>Daily summary</b>",
        "sum_none": "No signals in the last 24h.",
        "sum_count": "Signals (24h): {n}",
        "sum_best": "🏆 Best 3:",
        "sum_worst": "📉 Worst 3:",
        "sum_win": "✅ Win rate (7d):",
    },
}


def T(lang: str) -> dict:
    return TERMS.get(lang, TERMS["ar"])
